<?xml version="1.0"?>
<package format="3">
  <name>liftkit_hardware_interface</name>
  <version>0.1.0</version>
  <description>Elmo-based liftkit ros2_control hardware interface</description>
  <maintainer email="you@nasa.gov">Your Name</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>hardware_interface</depend>
  <depend>pluginlib</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_lifecycle</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
