controller_manager:
  ros__parameters:
    update_rate: 500  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    lift_position_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

lift_position_trajectory_controller:
  ros__parameters:
    joints:
      - ewellix_lift_lower_to_higher

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 50.0
    action_monitor_rate: 20.0

    allow_partial_joints_goal: false
    open_loop_control: false
